import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Animated_Cursor from "@/components/Animated_Cursor";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
        {children}
        <Animated_Cursor/>
      </body>
    </html>
  );
}
