import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AnimatedCursor from "react-animated-cursor"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
        {children}
        <AnimatedCursor
          innerSize={10}
          outerSize={10}
          color='4,199, 11'
          outerAlpha={0.2}
          innerScale={0.7}
          outerScale={5}
        />
      </body>
    </html>
  );
}
