import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AnimatedCursor from "react-animated-cursor";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="dark">
      <body className={inter.className}>
        {children}
        <AnimatedCursor
          innerSize={8} // Decreased inner size
          outerSize={20} // Increased outer size
          color="255,255, 255" // Changed color to red
          outerAlpha={0.4} // Increased outer transparency
          innerScale={0.5} // Decreased inner scale
          outerScale={8} // Increased outer scale
        />
      </body>
    </html>
  );
}
